import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../@core/style/globals.css";
import Header from "@/@core/components/reusable/Header";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "1009 | Админский панель",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${inter.className} text-main_black`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
